import type { MetadataRoute } from "next";

// Web App Manifest, auto-served at /manifest.webmanifest via Next.js
// file convention. Powers iOS "Add to Home Screen" + Android PWA
// install. Icons are generated by sibling icon.tsx + apple-icon.tsx
// at request time; we don't ship checked-in PNGs.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "PFA Cage Rentals",
    short_name: "PFA Rentals",
    description: "Cage, bullpen, and weight-room rental tracking for PFA Baseball.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    icons: [
      { src: "/icon", sizes: "192x192", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
